const SUGGESTION_URL = import.meta.env.VITE_SUGGESTION_URL;
const RECOMMENDATION_URL = import.meta.env.VITE_RECOMMENDATION_URL;
const SEARCH_URL = import.meta.env.VITE_SEARCH_URL;

export { SUGGESTION_URL, RECOMMENDATION_URL, SEARCH_URL };